# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Ea7i6k1g5Ss_DTLd2i4YNfo3PxIkque
"""

!pip install jupyter-dash dash-bootstrap-components

import pandas as pd
df = pd.read_csv("/content/dataframe_cleaned_final.csv")

# INDIAN STARTUP ECOSYSTEM

import os
import warnings
from datetime import datetime
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.io as pio

# Import JupyterDash
# from jupyter_dash import JupyterDash
import dash
from dash import dcc, html, Input, Output, State
import dash_bootstrap_components as dbc

# Suppress warnings and set default theme
warnings.simplefilter(action='ignore', category=FutureWarning)
pio.templates.default = "plotly_dark"

# 2. LOAD AND CLEAN DATA (ONCE)


DATA_FILE_PATH = '/content/dataframe_cleaned_final.csv'

try:
    df = pd.read_csv('/content/dataframe_cleaned_final.csv')
except FileNotFoundError:
    print("="*50)
    print(f"ERROR: Data file not found.")
    print(f"Please make sure you have uploaded '{DATA_FILE_PATH}' to the Colab file sidebar.")
    print("="*50)
    raise

# Create a single, processed DataFrame for all tabs
df_processed = df.copy()

# --- 2.1 Clean Dates & Year ---
date_col = 'Date' if 'Date' in df_processed.columns else 'Date dd/mm/yyyy'
if date_col in df_processed.columns:
    df_processed[date_col] = pd.to_datetime(df_processed[date_col], errors='coerce')
    df_processed['Year'] = df_processed[date_col].dt.year
else:
    df_processed['Year'] = 0
df_processed['Year'] = df_processed['Year'].fillna(0).astype(int)
df_processed['Deal Count'] = 1

# --- 2.2 Clean City Location ---
city_col = 'City Location' if 'City Location' in df_processed.columns else 'City  Location'
if city_col in df_processed.columns:
    df_processed[city_col] = df_processed[city_col].fillna('Unknown').astype(str).str.strip()
    if city_col != 'City Location':
        df_processed = df_processed.rename(columns={city_col: 'City Location'})
else:
    df_processed['City Location'] = 'Unknown'

# --- 2.3 Clean Amount in USD ---
if 'Amount in USD' in df_processed.columns:
    df_processed['Amount in USD'] = pd.to_numeric(
        df_processed['Amount in USD'].astype(str).str.replace(r'[$,]', '', regex=True),
        errors='coerce'
    ).fillna(0.0)
else:
    df_processed['Amount in USD'] = 0.0

# --- 2.4 Clean Industry Vertical ---
df_processed['Industry Vertical'] = df_processed.get('Industry Vertical', pd.Series(dtype=str)).fillna('Unknown').astype(str)

# --- 2.5 Clean Investment Type (for Tab 3) ---
df_processed['Investment Type'] = df_processed.get('Investment Type', pd.Series(dtype=str)).fillna('Unknown').astype(str)

# --- 2.6 Clean Investors Name (for Tab 5) ---
df_processed['Investors Name'] = df_processed.get('Investors Name', pd.Series(dtype=str)).fillna('Undisclosed').astype(str)
df_processed['Investors Name'] = df_processed['Investors Name'].str.replace(' and others', '', regex=False).str.strip()

print("Data loaded and cleaned successfully.")

# 3. HELPER FUNCTIONS & DICTIONARIES (ALL SCRIPTS)

# --- 3.1 For Tab 4: Resilience Index ---
def calc_resilience(df_slice):
    sector_year = (
        df_slice
        .groupby(['Industry Vertical', 'Year'], as_index=False)['Amount in USD']
        .sum()
    )
    stats = (
        sector_year
        .groupby('Industry Vertical')['Amount in USD']
        .agg(['mean', 'std', 'count'])
        .reset_index()
    )
    stats = stats[stats['count'] >= 2].copy()
    stats['Resilience Index'] = 1 - (stats['std'] / stats['mean'].replace(0, np.nan))
    stats['Resilience Index'] = stats['Resilience Index'].replace([np.inf, -np.inf], np.nan)
    stats['Resilience Index'] = stats['Resilience Index'].fillna(-1)
    stats = stats.sort_values('Resilience Index', ascending=False)
    return stats.reset_index(drop=True)

# --- 3.2 For Tab 5: Top Investors ---
def get_top_investors(df_slice, top_n=15):
    investor_list = []
    investors_data = df_slice[
        (df_slice['Investors Name'] != 'Undisclosed') &
        (df_slice['Investors Name'] != '')
    ]['Investors Name']
    for investor_string in investors_data:
        investors = [i.strip() for i in investor_string.split(',') if i.strip()]
        investor_list.extend(investors)
    investor_counts = pd.Series(investor_list).value_counts().reset_index()
    investor_counts.columns = ['Investor Name', 'Number of Investments']
    top_investors = investor_counts.head(top_n).copy()
    return top_investors.iloc[::-1].reset_index(drop=True)

# --- 3.3 For Tab 1 (Upgraded Trend Chart) ---
def get_funding_trend(df_slice):
    df_valid = df_slice[df_slice['Year'] > 0].copy()
    funding_by_year = df_valid.groupby('Year')['Amount in USD'].sum().reset_index()
    funding_by_year.columns = ['Year', 'Total Funding (USD)']
    funding_by_year['Total Funding (Billions USD)'] = funding_by_year['Total Funding (USD)'] / 1e9
    return funding_by_year

# --- 3.4 For Tab 6: Geographic Hotspots ---
city_coords = {
    "Bengaluru": (12.9716, 77.5946), "Gurgaon": (28.4595, 77.0266),
    "New Delhi": (28.6139, 77.2090), "Mumbai": (19.0760, 72.8777),
    "Chennai": (13.0827, 80.2707), "Pune": (18.5204, 73.8567),
    "Noida": (28.5355, 77.3910), "Hyderabad": (17.3850, 78.4867),
    "Ahmedabad": (23.0225, 72.5714), "Jaipur": (26.9124, 75.7873),
    "Kolkata": (22.5726, 88.3639), "Indore": (22.7196, 75.8577),
    "Chandigarh": (30.7333, 76.7794), "Coimbatore": (11.0168, 76.9558),
    "Vadodara": (22.3072, 73.1812), "Goa": (15.2993, 74.1240),
    "Surat": (21.1702, 72.8311), "Kanpur": (26.4499, 80.3319),
    "Kochi": (9.9312, 76.2673), "Lucknow": (26.8467, 80.9462),
    "Bhubaneswar": (20.2961, 85.8245), "Udaipur": (24.5854, 73.7125),
    "Agra": (27.1767, 78.0081), "Bhopal": (23.2599, 77.4126),
    "Gaya": (24.7914, 85.0002), "Gwalior": (26.2183, 78.1828),
    "Hubli": (15.3647, 75.1240), "Jodhpur": (26.2389, 73.0243),
    "Karur": (10.9601, 78.0766), "Kozhikode": (11.2588, 75.7804),
    "Nagpur": (21.1458, 79.0882), "Panaji": (15.4909, 73.8278),
    "Patna": (25.5941, 85.1376), "Rourkela": (22.2604, 84.8536),
    "Siliguri": (26.7271, 88.3953), "Srinagar": (34.0837, 74.7973),
    "Trivandrum": (8.5241, 76.9366), "Udupi": (13.3409, 74.7421),
    "Varanasi": (25.3176, 82.9739), "Belgaum": (15.8497, 74.4977),
    "San Francisco": (37.7749, -122.4194), "New York": (40.7128, -74.0060),
    "Menlo Park": (37.4529, -122.1817), "Palo Alto": (37.4419, -122.1430),
    "Boston": (42.3601, -71.0589), "London": (51.5074, -0.1278),
    "Singapore": (1.3521, 103.8198), "Seattle": (47.6062, -122.3321),
    "San Jose": (37.3382, -121.8863), "Santa Monica": (34.0195, -118.4912),
    "Dallas": (32.7767, -96.7970), "Burnsville": (44.7677, -93.2777),
    "Nairobi": (-1.2921, 36.8219),
    "Unknown": (None, None), "Not Specified": (None, None)
}

def prep_city_agg(df_slice):
    tmp = df_slice[['City Location', 'Amount in USD']].copy()
    city_agg = (tmp.groupby('City Location', as_index=False)['Amount in USD'].sum()
                   .sort_values('Amount in USD', ascending=False)
                   .reset_index(drop=True))
    coords_df = pd.DataFrame({
        'City Location': list(city_coords.keys()),
        'Latitude':  [city_coords.get(c, (None, None))[0] for c in city_coords],
        'Longitude': [city_coords.get(c, (None, None))[1] for c in city_coords],
    })
    joined = city_agg.merge(coords_df, on='City Location', how='left')
    return joined

# 📊 PRE-COMPUTE LAYOUT DATA & OPTIONS

# --- For Filters ---
valid_years = df_processed[df_processed['Year'] > 0]['Year']
MIN_YEAR = int(valid_years.min()) if not valid_years.empty else 2015
MAX_YEAR = int(valid_years.max()) if not valid_years.empty else 2024
DEFAULT_YEARS = [MIN_YEAR, MAX_YEAR]

industry_options = [{"label": x, "value": x} for x in sorted(df_processed['Industry Vertical'].unique())]
city_options = [{"label": x, "value": x} for x in sorted(df_processed['City Location'].unique())]
stage_options = [{"label": x, "value": x} for x in sorted(df_processed['Investment Type'].unique())]

# --- For Tab 2 (Static Aggregation) ---
sector_funding = df_processed.groupby('Industry Vertical')['Amount in USD'].sum().reset_index()
sector_funding = sector_funding[sector_funding['Amount in USD'] > 1_000_000]
sector_funding = sector_funding.sort_values(by='Amount in USD', ascending=False)
total_funding_kpi = sector_funding['Amount in USD'].sum()
num_verticals_kpi = len(sector_funding)


# ==============================================================================
# 5. 🖥️ INITIALIZE DASH APP
# ==============================================================================


# app = JupyterDash(__name__, external_stylesheets=[dbc.themes.CYBORG])
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.CYBORG])
app.title = "Indian Startup Ecosystem Dashboard"

# ==============================================================================
# 6.  LAYOUT DEFINITION
# ==============================================================================

app.layout = dbc.Container(fluid=True, className="dbc", children=[

    # --- Main Title ---
    dbc.Row(
        dbc.Col(
            html.H1("📊 Indian Startup Ecosystem Dashboard",
                    className="text-center text-primary mb-4 pt-4"),
            width=12
        )
    ),

    # --- Tabbed Interface ---
    dcc.Tabs(id="main-tabs", value='tab-1-overview', children=[

        # ==================== TAB 1: OVERVIEW ====================
        dcc.Tab(label='Funding Trends', value='tab-1-overview', children=[
            dbc.Container(fluid=True, className="py-4", children=[
                dcc.Store(id="filtered-store"),
                dbc.Card(className="mb-4", body=True, children=[
                    dbc.Row([
                        dbc.Col(width=4, children=[
                            html.Label("Industry Vertical", className="fw-bold"),
                            dcc.Dropdown(id="industry-filter", options=industry_options, multi=True, placeholder="All industries")
                        ]),
                        dbc.Col(width=4, children=[
                            html.Label("City Location", className="fw-bold"),
                            dcc.Dropdown(id="city-filter", options=city_options, multi=True, placeholder="All cities")
                        ]),
                        dbc.Col(width=4, children=[
                            html.Label("Year Range", className="fw-bold"),
                            dcc.RangeSlider(
                                id="year-range", min=MIN_YEAR, max=MAX_YEAR, value=DEFAULT_YEARS,
                                marks={y: str(y) for y in range(MIN_YEAR, MAX_YEAR + 1, max(1, (MAX_YEAR - MIN_YEAR)//6 or 1))},
                                allowCross=False,
                                tooltip={"placement": "bottom", "always_visible": False}
                            )
                        ]),
                    ])
                ]),
                dbc.Row(className="mb-4", children=[
                    dbc.Col(dbc.Card(id="kpi-total", className="text-center p-3"), width=4),
                    dbc.Col(dbc.Card(id="kpi-deals", className="text-center p-3"), width=4),
                    dbc.Col(dbc.Card(id="kpi-avg", className="text-center p-3"), width=4),
                ]),
                dbc.Row([
                    dbc.Col(dcc.Graph(id="funding-trend-line-upgraded", style={'height': '500px'}), width=7),
                    dbc.Col(dcc.Graph(id="top-cities-bar", style={'height': '500px'}), width=5),
                ])
            ])
        ]), # End Tab 1

        # ==================== TAB 2: VERTICAL DEEP DIVE ====================
        dcc.Tab(label='Vertical Deep Dive', value='tab-2-verticals', children=[
            dbc.Container(fluid=True, className="py-4", children=[
                dbc.Row(
                    dbc.Col(
                        dbc.Card(body=True, children=[
                            html.H3(f"Total Funding Analyzed: ${total_funding_kpi:,.0f}", className="text-info"),
                            html.H3(f"Total Verticals (>$1M): {num_verticals_kpi}", className="text-info mb-3"),
                            html.Hr(),
                            html.Label('Select Top N Verticals:', className='fw-bold'),
                            dcc.Slider(
                                id='top-n-slider-verticals', min=5, max=50, step=1, value=15,
                                marks={i: str(i) for i in range(5, 51, 5)}
                            )
                        ]),
                        width=12
                    ),
                    className="mb-4"
                ),
                dbc.Row([
                    dbc.Col(dcc.Graph(id='treemap-chart', style={'height': '600px'}), width=6),
                    dbc.Col(dcc.Graph(id='bar-chart', style={'height': '600px'}), width=6),
                ])
            ])
        ]), # End Tab 2

        # ==================== TAB 3: STAGE ANALYSIS ====================
        dcc.Tab(label='Stage Analysis', value='tab-3-stage', children=[
            dbc.Container(fluid=True, className="py-4", children=[
                dbc.Card(className="mb-4", body=True, children=[
                    dbc.Row([
                        dbc.Col(width=4, children=[
                            html.Label("Industry Vertical", className="fw-bold"),
                            dcc.Dropdown(id="stage-industry-filter", options=industry_options, multi=True, placeholder="All industries")
                        ]),
                        dbc.Col(width=4, children=[
                            html.Label("City Location", className="fw-bold"),
                            dcc.Dropdown(id="stage-city-filter", options=city_options, multi=True, placeholder="All cities")
                        ]),
                        dbc.Col(width=4, children=[
                            html.Label("Year Range", className="fw-bold"),
                            dcc.RangeSlider(
                                id="stage-year-slider", min=MIN_YEAR, max=MAX_YEAR, value=DEFAULT_YEARS,
                                marks={y: str(y) for y in range(MIN_YEAR, MAX_YEAR + 1, max(1, (MAX_YEAR - MIN_YEAR)//6 or 1))},
                                allowCross=False
                            )
                        ]),
                    ])
                ]),
                dbc.Row([
                    dbc.Col(dcc.Graph(id='stage-treemap', style={'height': '600px'}), width=6),
                    dbc.Col(dcc.Graph(id='stage-bar', style={'height': '600px'}), width=6),
                ])
            ])
        ]), # End Tab 3

        # ==================== TAB 4: RESILIENCE INDEX ====================
        dcc.Tab(label='Resilience Index', value='tab-4-resilience', children=[
            dbc.Container(fluid=True, className="py-4", children=[
                dbc.Card(className="mb-4", body=True, children=[
                    dbc.Row([
                        dbc.Col(width=8, children=[
                            html.Label("Select Year Range", className="text-light fw-bold small"),
                            dcc.RangeSlider(
                                id='year-slider', min=MIN_YEAR, max=MAX_YEAR, step=1,
                                marks={str(y): str(y) for y in range(MIN_YEAR, MAX_YEAR + 1)},
                                value=DEFAULT_YEARS
                            )
                        ]),
                        dbc.Col(width=4, children=[
                            html.Label("Filter by City (optional)", className="text-light fw-bold small"),
                            dcc.Dropdown(
                                id='city-dropdown', options=city_options,
                                value=None, placeholder="All Cities", clearable=True
                            )
                        ]),
                    ])
                ]),
                dbc.Row(dbc.Col(dcc.Graph(id='resilience-bar', style={'height': '550px'}), width=12)),
                dbc.Row(dbc.Col(
                    dbc.Alert(
                        "💡 Interpretation: The Funding Resilience Index (1 - std/mean) measures the stability of capital flow. "
                        "Higher values indicate more consistent yearly funding.",
                        color="dark", class_name="text-light p-3 border-info mt-3"
                    )
                ))
            ])
        ]), # End Tab 4

        # ==================== TAB 5: TOP INVESTORS ====================
        dcc.Tab(label='Top Investors', value='tab-5-investors', children=[
            dbc.Container(fluid=True, className="py-4", children=[
                dbc.Card(className="mb-4", body=True, children=[
                    dbc.Row([
                        dbc.Col(width=8, children=[
                            html.Label("Select Year Range", className="text-light fw-bold small"),
                            dcc.RangeSlider(
                                id='investor-year-slider', min=MIN_YEAR, max=MAX_YEAR, step=1,
                                marks={str(y): str(y) for y in range(MIN_YEAR, MAX_YEAR + 1)},
                                value=DEFAULT_YEARS
                            )
                        ]),
                        dbc.Col(width=4, children=[
                            html.Label("Filter by City (optional)", className="text-light fw-bold small"),
                            dcc.Dropdown(
                                id='investor-city-dropdown', options=city_options,
                                value=None, placeholder="All Cities", clearable=True
                            )
                        ]),
                    ])
                ]),
                dbc.Row(dbc.Col(dcc.Graph(id='investor-bar-chart', style={'height': '600px'}), width=12)),
                dbc.Row(dbc.Col(
                    dbc.Alert(
                        "Note: This chart displays the top 15 investors by *count* of investments, excluding 'Undisclosed'.",
                        color="dark", class_name="text-light p-3 border-info mt-3"
                    )
                ))
            ])
        ]), # End Tab 5

        # ==================== TAB 6: GEOGRAPHIC HOTSPOTS ====================
        dcc.Tab(label='Geographic Hotspots', value='tab-6-geo', children=[
            dbc.Container(fluid=True, className="py-4", children=[
                dbc.Card(className="mb-4", body=True, children=[
                    dbc.Row([
                        dbc.Col(width=4, children=[
                            html.Label("Industry Vertical", className="fw-bold"),
                            dcc.Dropdown(id="geo-industry-filter", options=industry_options, multi=True, placeholder="All industries")
                        ]),
                        dbc.Col(width=4, children=[
                            html.Label("Year Range", className="fw-bold"),
                            dcc.RangeSlider(
                                id="geo-year-slider", min=MIN_YEAR, max=MAX_YEAR, value=DEFAULT_YEARS,
                                marks={y: str(y) for y in range(MIN_YEAR, MAX_YEAR + 1, max(1, (MAX_YEAR - MIN_YEAR)//6 or 1))}
                            )
                        ]),
                        dbc.Col(width=4, children=[
                            html.Label("Map Region", className="fw-bold"),
                            dcc.Dropdown(
                                id='scope',
                                options=[
                                    {'label':'World','value':'world'}, {'label':'India','value':'india'},
                                    {'label':'Asia','value':'asia'}, {'label':'USA','value':'usa'},
                                    {'label':'Europe','value':'europe'}
                                ],
                                value='world', clearable=False
                            )
                        ]),
                    ], className="mb-3"),
                    dbc.Row([
                        dbc.Col(width=8, children=[
                             html.Label("Top N Cities:", className="fw-bold"),
                            dcc.Slider(
                                id='top-n-slider-geo', min=5, max=50, step=1, value=15,
                                marks={i: str(i) for i in range(5, 51, 5)}
                            )
                        ]),
                        dbc.Col(width=4, className="pt-4", children=[
                            dcc.Checklist(
                                id='exclude-unknown',
                                options=[{'label': "Exclude 'Unknown' / 'Not Specified'", 'value':'exclude'}],
                                value=['exclude'],
                            )
                        ])
                    ])
                ]),
                dbc.Row([
                    dbc.Col(dcc.Graph(id='geo-bar-chart', style={'height': '600px'}), width=6),
                    dbc.Col(dcc.Graph(id='geo-map-chart', style={'height': '600px'}), width=6),
                ])
            ])
        ]), # End Tab 6

    ]), # End dcc.Tabs

    html.Footer("Dashboard on Indian Startup Ecosystem",
                className="text-center text-secondary mt-4 mb-4 small")
])


# ==============================================================================
# 7. CALLBACKS
# ==============================================================================

# --- Empty Figure Generator (for 'No Data') ---
def create_empty_fig(message="No data for selected filters."):
    fig = px.bar()
    fig.update_layout(
        template='plotly_dark',
        title_x=0.5,
        xaxis=dict(visible=False),
        yaxis=dict(visible=False),
        annotations=[dict(
            text=message,
            showarrow=False, x=0.5, y=0.5, xref="paper", yref="paper",
            font=dict(size=16, color="white")
        )],
    )
    return fig

# ------------------------------------------------------------------------------
# CALLBACKS FOR TAB 1: OVERVIEW
# ------------------------------------------------------------------------------

# --- 1.1: Filter data and store it ---
@app.callback(
    Output("filtered-store", "data"),
    Input("industry-filter", "value"),
    Input("city-filter", "value"),
    Input("year-range", "value"),
)
def filter_and_store_data(industry_values, city_values, year_range):
    d = df_processed
    if industry_values:
        d = d[d["Industry Vertical"].isin(industry_values)]
    if city_values:
        d = d[d["City Location"].isin(city_values)]

    year_min, year_max = int(year_range[0]), int(year_range[1])
    d = d[(d["Year"] >= year_min) & (d["Year"] <= year_max)]

    return d.to_dict("records")

# --- 1.2: Update KPIs ---
@app.callback(
    Output("kpi-total", "children"),
    Output("kpi-deals", "children"),
    Output("kpi-avg", "children"),
    Input("filtered-store", "data")
)
def update_kpis(filtered_data):
    if not filtered_data:
        k_total = "$ 0"
        k_deals = "0"
        k_avg = "$ 0"
    else:
        d = pd.DataFrame(filtered_data)
        total_funding = d["Amount in USD"].sum()
        total_deals = d["Deal Count"].sum()
        avg_deal = total_funding / total_deals if total_deals else 0

        k_total = f"${total_funding:,.0f}"
        k_deals = f"{total_deals:,}"
        k_avg = f"${avg_deal:,.0f}"

    return (
        [html.H4("Total Funding (USD)", className="text-secondary"), html.H2(k_total, className="text-success")],
        [html.H4("Number of Deals", className="text-secondary"), html.H2(k_deals, className="text-info")],
        [html.H4("Average Deal Size", className="text-secondary"), html.H2(k_avg, className="text-warning")]
    )

# --- 1.3: Update Upgraded Funding Trend Line Chart ---
@app.callback(
    Output("funding-trend-line-upgraded", "figure"),
    Input("filtered-store", "data")
)
def update_trend_chart(filtered_data):
    if not filtered_data:
        return create_empty_fig()

    dff = pd.DataFrame(filtered_data)
    funding_stats = get_funding_trend(dff)

    if funding_stats.empty:
        return create_empty_fig()

    fig = px.line(
        funding_stats,
        x='Year',
        y='Total Funding (Billions USD)',
        text='Total Funding (Billions USD)',
        title=f"Total Funding Amount Invested Per Year",
        labels={'Total Funding (Billions USD)': 'Total Funding (Billions USD)', 'Year': 'Year'},
        markers=True
    )
    fig.update_traces(
        line=dict(color='#00CC96', width=4),
        marker=dict(size=10, symbol='circle', line=dict(width=1, color='White')),
        texttemplate='%{y:.2f}B',
        textposition="top center",
        hovertemplate='%{x}<br>Funding: %{y:.2f}B<extra></extra>'
    )
    fig.update_layout(
        template='plotly_dark', title_x=0.5, hovermode="x unified",
        xaxis_title="Year", yaxis_title="Total Funding (Billions USD)"
    )
    fig.update_xaxes(
        tickvals=funding_stats['Year'],
        tickformat='d'
    )
    return fig

# --- 1.4: Update Top Cities Bar Chart ---
@app.callback(
    Output("top-cities-bar", "figure"),
    Input("filtered-store", "data")
)
def update_cities_chart(filtered_data):
    if not filtered_data:
        return create_empty_fig()

    d = pd.DataFrame(filtered_data)
    top_cities = d.groupby("City Location", as_index=False)["Amount in USD"].sum().sort_values("Amount in USD", ascending=False).head(10)

    if top_cities.empty:
        return create_empty_fig()

    fig_bar = px.bar(
        top_cities, x="Amount in USD", y="City Location",
        orientation="h", title="Top 10 Cities by Funding"
    )
    fig_bar.update_traces(hovertemplate='%{y}<br>Funding: %{x:,.0f}<extra></extra>')
    fig_bar.update_layout(
        template='plotly_dark', yaxis={"categoryorder": "total ascending"}
    )
    return fig_bar

# ------------------------------------------------------------------------------
# CALLBACK FOR TAB 2: VERTICAL DEEP DIVE
# ------------------------------------------------------------------------------
@app.callback(
    Output('treemap-chart', 'figure'),
    Output('bar-chart', 'figure'),
    Input('top-n-slider-verticals', 'value')
)
def update_verticals_charts(n_value):
    top_n_data = sector_funding.head(n_value)

    fig_treemap = px.treemap(
        top_n_data,
        path=[px.Constant("All Verticals"), 'Industry Vertical'],
        values='Amount in USD',
        color='Amount in USD',
        color_continuous_scale='Blues',
        title=f'<b>Top {n_value} Verticals (Treemap)</b>'
    )
    fig_treemap.update_traces(
        hovertemplate='<b>%{label}</b><br>Funding: %{value:$,.0f}<br>Share: %{percentRoot:.2%}'
    )
    fig_treemap.update_layout(template='plotly_dark')

    fig_bar = px.bar(
        top_n_data,
        x='Amount in USD',
        y='Industry Vertical',
        orientation='h',
        title=f'<b>Top {n_value} Verticals (Bar Chart)</b>'
    )
    fig_bar.update_layout(
        yaxis={'categoryorder':'total ascending'},
        template='plotly_dark'
    )
    return fig_treemap, fig_bar

# ------------------------------------------------------------------------------
# CALLBACK FOR TAB 3: STAGE ANALYSIS
# ------------------------------------------------------------------------------
@app.callback(
    Output('stage-treemap', 'figure'),
    Output('stage-bar', 'figure'),
    Input('stage-year-slider', 'value'),
    Input('stage-city-filter', 'value'),
    Input('stage-industry-filter', 'value')
)
def update_stage_charts(year_range, city_values, industry_values):
    dff = df_processed

    start, end = year_range
    dff = dff[(dff['Year'] >= start) & (dff['Year'] <= end)]

    if city_values:
        dff = dff[dff['City Location'].isin(city_values)]

    if industry_values:
        dff = dff[dff['Industry Vertical'].isin(industry_values)]

    df_agg = dff.groupby(['Industry Vertical', 'Investment Type'], as_index=False)['Amount in USD'].sum()
    df_agg = df_agg[df_agg['Amount in USD'] > 0]

    top_10_industries = df_agg.groupby('Industry Vertical')['Amount in USD'].sum().nlargest(10).index
    df_agg_top = df_agg[df_agg['Industry Vertical'].isin(top_10_industries)]

    if df_agg_top.empty:
        return create_empty_fig(), create_empty_fig()

    fig_treemap = px.treemap(
        df_agg_top,
        path=[px.Constant('All Industries'), 'Industry Vertical', 'Investment Type'],
        values='Amount in USD',
        title='<b>Funding by Vertical and Stage (Treemap)</b>',
        color='Investment Type'
    )
    fig_treemap.update_traces(
        hovertemplate='<b>%{label}</b><br>Amount: %{value:$,.0f}<br>Parent: %{parent}'
    )
    fig_treemap.update_layout(template='plotly_dark')

    fig_bar = px.bar(
        df_agg_top,
        y='Industry Vertical',
        x='Amount in USD',
        color='Investment Type',
        orientation='h',
        title='<b>Funding by Vertical and Stage (Top 10 Verticals)</b>',
        barmode='stack'
    )
    fig_bar.update_layout(
        template='plotly_dark',
        yaxis={'categoryorder': 'total descending'},
        xaxis_title='Total Funding (USD)',
        yaxis_title='Industry Vertical'
    )

    return fig_treemap, fig_bar


# ------------------------------------------------------------------------------
# CALLBACK FOR TAB 4: RESILIENCE INDEX
# ------------------------------------------------------------------------------
@app.callback(
    Output('resilience-bar', 'figure'),
    Input('year-slider', 'value'),
    Input('city-dropdown', 'value')
)
def update_resilience(year_range, selected_city):
    start, end = year_range
    dff = df_processed[(df_processed['Year'] >= start) & (df_processed['Year'] <= end)].copy()
    if selected_city:
        dff = dff[dff['City Location'] == selected_city].copy()

    stats = calc_resilience(dff)

    if stats.empty:
        return create_empty_fig()

    fig = px.bar(stats.head(15).sort_values('Resilience Index', ascending=True),
                 x='Resilience Index', y='Industry Vertical',
                 orientation='h', color='Resilience Index',
                 color_continuous_scale='Tealgrn',
                 title="Top 15 Most Funding-Resilient Sectors")
    fig.update_layout(template='plotly_dark', title_x=0.5,
                      xaxis_title="Resilience Index (1 - std/mean)",
                      yaxis_title="Industry Vertical")
    return fig

# ------------------------------------------------------------------------------
# CALLBACK FOR TAB 5: TOP INVESTORS
# ------------------------------------------------------------------------------
@app.callback(
    Output('investor-bar-chart', 'figure'),
    Input('investor-year-slider', 'value'),
    Input('investor-city-dropdown', 'value')
)
def update_investor_chart(year_range, selected_city):
    start, end = year_range
    dff = df_processed[(df_processed['Year'] >= start) & (df_processed['Year'] <= end)].copy()
    if selected_city:
        dff = dff[dff['City Location'] == selected_city].copy()

    top_stats = get_top_investors(dff, top_n=15)

    if top_stats.empty:
        return create_empty_fig("No investor data found. Try broader filters.")

    fig = px.bar(
        top_stats,
        x='Number of Investments',
        y='Investor Name',
        orientation='h',
        color='Number of Investments',
        color_continuous_scale='Sunsetdark',
        title=f"Top 15 Most Active Investors ({start}–{end})"
    )
    fig.update_traces(marker_line_width=0, hovertemplate='%{y}<br>Investments: %{x}<extra></extra>')
    fig.update_layout(
        template='plotly_dark', title_x=0.5,
        xaxis_title="Total Number of Investments", yaxis_title="Investor Name",
        margin=dict(l=200),
        coloraxis_colorbar=dict(title="Count")
    )
    fig.update_yaxes(categoryorder='array', categoryarray=top_stats['Investor Name'].tolist())
    return fig

# ------------------------------------------------------------------------------
# CALLBACK FOR TAB 6: GEOGRAPHIC HOTSPOTS
# ------------------------------------------------------------------------------
@app.callback(
    Output('geo-bar-chart', 'figure'),
    Output('geo-map-chart', 'figure'),
    Input('geo-year-slider', 'value'),
    Input('geo-industry-filter', 'value'),
    Input('top-n-slider-geo', 'value'),
    Input('scope', 'value'),
    Input('exclude-unknown', 'value')
)
def update_geo_figs(year_range, industry_values, top_n, scope, exclude_vals):

    start, end = year_range
    dff = df_processed[(df_processed['Year'] >= start) & (df_processed['Year'] <= end)].copy()
    if industry_values:
        dff = dff[dff['Industry Vertical'].isin(industry_values)].copy()

    city_agg = prep_city_agg(dff)

    d = city_agg.copy()

    if 'exclude' in (exclude_vals or []):
        exclude_list = ['unknown', 'not specified']
        d = d[~d['City Location'].str.lower().isin(exclude_list)]

    d_map = d.dropna(subset=['Latitude', 'Longitude'])

    if d.empty:
        return create_empty_fig(), create_empty_fig()

    d_top = d.nlargest(int(top_n), 'Amount in USD')
    d_map_top = d_map.merge(d_top[['City Location']], on='City Location', how='inner')

    # Bar chart
    fig_bar = px.bar(
        d_top.sort_values('Amount in USD', ascending=True),
        x='Amount in USD', y='City Location', orientation='h',
        labels={'Amount in USD':'Total Funding (USD)', 'City Location':'City'},
        title=f"Top {len(d_top)} Cities by Startup Funding"
    )
    fig_bar.update_layout(template='plotly_dark', margin=dict(l=140))

    # Geo map
    if d_map_top.empty:
        fig_geo = create_empty_fig("Map: no coordinates available for selected cities")
    else:
        d_map_top = d_map_top.assign(size=np.sqrt(d_map_top['Amount in USD']))
        fig_geo = px.scatter_geo(
            d_map_top,
            lat='Latitude', lon='Longitude',
            size='size',
            hover_name='City Location',
            hover_data={'Amount in USD':':,.0f', 'Latitude':False, 'Longitude':False, 'size':False},
            title="Hotspots Map — Bubbles sized by total funding"
        )

        # --- START OF CHANGES ---

        if scope == 'india':

    # Focus map manually on India (approx. bounding box)
          fig_geo.update_geos(
          projection_type='natural earth',
          visible=True,
          resolution=50,
          showcountries=True,
          countrycolor="Gray",
          lonaxis_range=[68, 98],   # longitude range of India
          lataxis_range=[6, 38],    # latitude range of India
          center=dict(lat=22, lon=80)
                        )
        else:

            fig_geo.update_geos(
                projection_type='natural earth',
                visible=True,
                showcountries=True,
                countrycolor="Gray",
                resolution=50
            )

        # Note: The default 'world' scope will apply if scope is 'world' or None

        # --- END OF CHANGES ---

        fig_geo.update_layout(template='plotly_dark', margin=dict(t=60, b=0))

    return fig_bar, fig_geo

# ==============================================================================
# 8. RUN THE APP
# ==============================================================================

# ---  Run with mode='external' to get the public URL ---
if __name__ == '__main__':
    print("Starting Dash app...")
    app.run(jupyter_mode='external', port=8050)

