# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZbnfYp7YBnI4OMi9v0VC4Ha1tEjDDptD
"""

!pip -q install --upgrade pip
!pip -q install streamlit cloudflared pandas matplotlib seaborn

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import numpy as np
# import re
# from matplotlib.colors import LinearSegmentedColormap
# from itertools import combinations
# import pydeck as pdk
# import plotly.express as px
# 
# 
# 
# st.set_page_config(layout="wide", page_title="StartUp Funding Analysis", page_icon="[*]")
# 
# # ===========================
# # THEME & PALETTE (Light)
# # ===========================
# COL_BRIDGE = "#D02E6B"   # Deep Pink
# COL_GROWTH = "#F65A45"   # Orange-Pink
# COL_LATE   = "#FCAE4A"   # Orange
# COL_SEED   = "#FFD36E"   # Light Yellow-Orange
# COL_COUNT  = "#FCA77E"   # Muted Orange (lines / counts)
# 
# PALETTE_SEQ = [COL_BRIDGE, COL_GROWTH, COL_LATE, COL_SEED, COL_COUNT]
# 
# ROUND_COLOR_MAP = {
#     "pre-seed": COL_SEED, "seed": COL_SEED, "angel": COL_SEED,
#     "series a": COL_GROWTH, "series b": COL_GROWTH, "series c": COL_GROWTH,
#     "bridge": COL_BRIDGE, "mezzanine": COL_BRIDGE,
#     "late": COL_LATE, "series d": COL_LATE, "pre-ipo": COL_LATE,
# }
# 
# # ---- CSS (keep your theme)
# st.markdown(
#     """
#     <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700&family=Roboto:wght@400;500&display=swap" rel="stylesheet">
#     <style>
#       :root { --bg:#fff; --surface:#f7f7f8; --text:#111827; --muted:#4b5563; --border:#e5e7eb; }
#       .stApp { background: var(--bg); color: var(--text); }
#       [data-testid="stSidebar"] { background: var(--surface); color: var(--text); border-right:1px solid var(--border); }
#       .block-container { padding-top:.8rem; padding-bottom:1.5rem; }
#       h1,h2,h3 { font-family:'Montserrat',Roboto,system-ui,sans-serif; letter-spacing:.2px; }
#       .stMarkdown,.stText,.stDataFrame,.stMetric,.stSelectbox,.stRadio,.stButton,.stTable { font-family:'Roboto',system-ui,-apple-system,Segoe UI,Roboto,sans-serif; }
#       .stDataFrame thead tr th { background:var(--surface); color:var(--text); }
#       .stDataFrame tbody tr td { color:var(--text); }
#       .stButton>button { border-radius:10px; border:1px solid var(--border); padding:.45rem .9rem; font-weight:600; }
#       .section { padding:.2rem 0 .9rem 0; border-bottom:1px solid var(--border); margin-bottom:.9rem; }
#       header[data-testid="stHeader"]{display:none!important;}
#       div.block-container{padding-top:1rem;}
#     </style>
#     """, unsafe_allow_html=True
# )
# 
# plt.rcParams.update({
#     "axes.facecolor":"#ffffff","figure.facecolor":"#ffffff","axes.edgecolor":"#e5e7eb",
#     "axes.labelcolor":"#111827","xtick.color":"#111827","ytick.color":"#111827",
#     "grid.color":"#e5e7eb","grid.linestyle":"-","grid.alpha":0.6,"font.size":11,
#     "axes.titleweight":"bold","axes.titlepad":10,"axes.grid":True,"legend.frameon":False,
# })
# sns.set_palette(PALETTE_SEQ)
# 
# def color_for_round(rname, default=COL_COUNT):
#     if not isinstance(rname,str): return default
#     key = rname.strip().lower()
#     for k,c in ROUND_COLOR_MAP.items():
#         if k in key: return c
#     return default
# 
# def style_axes(ax):
#     for s in ax.spines.values():
#         s.set_edgecolor("#e5e7eb")
#     return ax
# 
# def gradient_fill(ax, x, y, color=COL_COUNT, alpha=0.18):
#     ax.fill_between(x, y, np.zeros_like(y), alpha=alpha, color=color)
# 
# def bar_labels(ax, bars, fmt="{:,.0f}"):
#     try: ax.bar_label(bars, fmt=fmt, label_type='edge', padding=2)
#     except: pass
# 
# # ===========================
# # Robust data loading
# # ===========================
# def load_first_available(paths):
#     last_err = None
#     for p in paths:
#         try:
#             return pd.read_csv(p, encoding="utf-8-sig"), p
#         except Exception as e:
#             last_err = e
#             try:
#                 return pd.read_csv(p, engine="python"), p
#             except Exception as e2:
#                 last_err = e2
#                 continue
#     raise FileNotFoundError(f"Could not open any of {paths}. Last error: {last_err}")
# 
# # column synonyms for your dataset
# COLMAP = {
#     "startup": {"startup","startup name","company","company/brand","company name","name"},
#     "vertical": {"vertical","sector","industry vertical","industry","category"},
#     "subvertical": {"subvertical","sub-vertical","sub sector","sub-sector","subsector"},
#     "city": {"city","location","headquarter","headquarters"},
#     "round": {"round","investment type","funding round","stage"},
#     "investors": {"investors","investor","investors name","investor names","investors (lead + others)"},
#     "amount": {"amount","amount (in inr cr)","amount in inr cr","amount in cr","amount(in inr cr)","amount ($)","amount (usd)","amount in usd"},
#     "date": {"date","announced date","announcement date","funded date","funding date"},
#     "year": {"year"},
#     "month": {"month"},
# }
# 
# MONTH_NAME = {m.lower():i for i,m in enumerate(["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"])}
# 
# def find_col(df, key):
#     """Find first matching column for semantic key; return canonical name if found."""
#     lower_cols = {c.lower():c for c in df.columns}
#     for cand in COLMAP.get(key, set()):
#         if cand in lower_cols: return lower_cols[cand]
#     # fuzzy contain
#     for c in lower_cols:
#         if key in c: return lower_cols[c]
#     return None
# 
# _amount_re = re.compile(r"[-+]?\d*\.?\d+")
# def parse_amount_to_cr(val):
#     """
#     Parse amount strings into Crores (float).
#     Handles: ₹/$, commas, 'Cr/Crore', 'Lakh/Lac', 'Mn/Million', 'Bn/Billion', 'Undisclosed'.
#     Heuristics: If 'lakh' -> /100 cr; 'mn/million' (assume USD or INR millions) -> convert to cr at 10 mn = 1 cr if INR-like.
#     If ambiguous, just return numeric found.
#     """
#     if pd.isna(val): return 0.0
#     s = str(val).strip().lower()
#     if not s or "undisclosed" in s or s in {"na","n/a","-","—","--","null"}:
#         return 0.0
# 
#     # detect unit hints
#     is_cr = (" cr" in s) or ("crore" in s)
#     is_lakh = (" lakh" in s) or (" lac" in s)
#     is_mn = (" mn" in s) or (" million" in s) or s.endswith("m")
#     is_bn = (" bn" in s) or (" billion" in s) or s.endswith("b")
# 
#     # extract first number
#     m = _amount_re.search(s.replace(",",""))
#     if not m: return 0.0
#     num = float(m.group())
# 
#     # scale by units
#     if is_cr:
#         return num
#     if is_lakh:
#         return num/100.0
#     if is_bn:
#         # 1 billion = 100 crores (for INR-like)
#         return num*100.0
#     if is_mn:
#         # assume 10 million ~ 1 crore
#         return num/10.0
# 
#     # currency signs ignored; treat raw number as crores if huge, else leave
#     return num
# 
# 
# def normalize_investors_cell(s):
#     """Split comma/& separated investors, trim & clean."""
#     if pd.isna(s): return []
#     s = str(s).replace("&", ",")
#     parts = [p.strip() for p in s.split(",") if p.strip()]
#     # drop placeholders like 'na'
#     parts = [p for p in parts if p.lower() not in {"na","n/a","null","-","—","--"}]
#     return parts
# 
# @st.cache_data(show_spinner=False)
# def load_data():
#     df, src = load_first_available(["dataframe_output.csv", "startup_cleaned.csv"])
# 
#     # lower + strip col names
#     df.columns = [c.strip() for c in df.columns]
# 
#     # map columns to canonical names (create if missing)
#     colmap_actual = {}
#     for key in COLMAP:
#         col = find_col(df, key)
#         if col is not None:
#             colmap_actual[key] = col
# 
#     # create canonical view
#     def getcol(key, default_series=None):
#         col = colmap_actual.get(key)
#         if col:
#             return df[col]
#         return default_series if default_series is not None else pd.Series([np.nan]*len(df))
# 
#     out = pd.DataFrame()
#     out["startup"]    = getcol("startup", pd.Series([""]*len(df))).astype(str).str.strip()
#     out["vertical"]   = getcol("vertical", pd.Series([""]*len(df))).astype(str).str.strip()
#     out["subvertical"]= getcol("subvertical", pd.Series([""]*len(df))).astype(str).str.strip()
#     out["city"]       = getcol("city", pd.Series([""]*len(df))).astype(str).str.strip()
#     out["round"]      = getcol("round", pd.Series([""]*len(df))).astype(str).str.strip()
#     out["investors"]  = getcol("investors", pd.Series([""]*len(df))).astype(str).str.strip()
# 
#     # amount -> crores
#     amt_series = getcol("amount", pd.Series([0]*len(df)))
#     out["amount"] = pd.to_numeric(amt_series, errors="coerce")
#     # if mostly NaN, try parsing strings
#     if out["amount"].isna().mean() > 0.5:
#       out["amount"] = amt_series.map(parse_amount_to_cr)
#     out["amount"] = out["amount"].fillna(0.0)
# 
#     # date / year / month
#     date_series = getcol("date")
#     # if year/month exist separately or as names
#     year_series = getcol("year")
#     month_series = getcol("month")
# 
#     # parse date
#     if date_series is not None and date_series.notna().any():
#         out["date"] = pd.to_datetime(date_series, errors="coerce", dayfirst=True, infer_datetime_format=True)
#     else:
#         out["date"] = pd.NaT
# 
#     # derive year/month if missing
#     if out["date"].notna().any():
#         out["year"] = out["date"].dt.year
#         out["month"] = out["date"].dt.month
#     else:
#         # try from provided year/month columns
#         if year_series is not None:
#             out["year"] = pd.to_numeric(year_series, errors="coerce").astype("Int64")
#         else:
#             out["year"] = pd.Series([pd.NA]*len(out), dtype="Int64")
#         if month_series is not None:
#             # allow names (Jan/January)
#             m = month_series.astype(str).str.strip().str.lower()
#             out["month"] = pd.to_numeric(m, errors="coerce")
#             mask = out["month"].isna()
#             if mask.any():
#                 out.loc[mask, "month"] = m[mask].str[:3].map({k[:3].lower():v for k,v in MONTH_NAME.items()}).astype("float")
#         else:
#             out["month"] = np.nan
# 
#     # Clean text columns
#     for c in ["startup","vertical","subvertical","city","round"]:
#         out[c] = out[c].fillna("").str.strip()
# 
#     # explode investors
#     inv_lists = out["investors"].map(normalize_investors_cell)
#     out["investors_list"] = inv_lists
#     df_exp = out.explode("investors_list", ignore_index=True).rename(columns={"investors_list":"investor"})
#     df_exp["investor"] = df_exp["investor"].fillna("").astype(str).str.strip()
# 
#     # final safety types
#     out["amount"] = out["amount"].astype(float)
#     # ensure ints when possible
#     if pd.api.types.is_numeric_dtype(out["year"]):
#         try: out["year"] = out["year"].astype("Int64")
#         except: pass
#     if pd.api.types.is_numeric_dtype(out["month"]):
#         try: out["month"] = out["month"].astype("Int64")
#         except: pass
# 
#     return out, df_exp, src
# 
# df, df_exp, data_src = load_data()
# 
# # ===========================
# # Plot helpers (unchanged visuals)
# # ===========================
# def plot_bar(x, y, title="", rotation=0, color_seq=PALETTE_SEQ, ylabel=None, xlabel=None, horizontal=False, fmt_vals="{:,.0f}"):
#     fig, ax = plt.subplots()
#     if horizontal:
#         bars = ax.barh(x, y, color=(color_seq if len(y)>1 else color_seq[0]))
#         bar_labels(ax, bars, fmt=fmt_vals)
#         ax.set_xlabel(xlabel or ""); ax.set_ylabel(ylabel or "")
#     else:
#         bars = ax.bar(x, y, color=(color_seq if len(y)>1 else color_seq[0]))
#         bar_labels(ax, bars, fmt=fmt_vals)
#         ax.set_ylabel(ylabel or ""); ax.set_xlabel(xlabel or "")
#     if rotation: ax.tick_params(axis="x", rotation=rotation)
#     ax.set_title(title); style_axes(ax)
#     st.pyplot(fig, use_container_width=True)
# 
# def plot_line_with_gradient(x, y, title="", color=COL_COUNT, xlabel=None, ylabel=None, xtick_rotation=0):
#     fig, ax = plt.subplots()
#     ax.plot(x, y, marker="o", linewidth=2.5, color=color)
#     gradient_fill(ax, np.arange(len(x)), np.array(y), color=color, alpha=0.18)
#     if xtick_rotation: ax.tick_params(axis="x", rotation=xtick_rotation)
#     ax.set_xlabel(xlabel or ""); ax.set_ylabel(ylabel or ""); ax.set_title(title)
#     style_axes(ax); st.pyplot(fig, use_container_width=True)
# 
# def plot_barh_top(series, title, xlabel, color_seq=PALETTE_SEQ, fmt_vals="{:,.0f}"):
#     s = series.dropna()
#     idx, vals = s.index.astype(str), s.values
#     plot_bar(idx[::-1], vals[::-1], title=title, horizontal=True, xlabel=xlabel, fmt_vals=fmt_vals, color_seq=color_seq)
# 
# def plot_stacked_barh_counts(pivot_df, title, xlabel="Count"):
#     fig, ax = plt.subplots()
#     left = np.zeros(len(pivot_df))
#     cols = list(pivot_df.columns)
#     col_colors = [color_for_round(c) for c in cols]
#     for c,col in zip(cols, col_colors):
#         vals = pivot_df[c].values
#         bars = ax.barh(pivot_df.index, vals, left=left, color=col, label=c)
#         left = left + vals
#     ax.set_xlabel(xlabel); ax.set_ylabel(""); ax.set_title(title)
#     ax.legend(loc="lower right", ncols=2, fontsize=9)
#     style_axes(ax); st.pyplot(fig, use_container_width=True)
# 
# def top_co_investor_pairs(df_source, top_n=15):
#     if "investors" not in df_source.columns: return pd.DataFrame(columns=["pair","count"])
#     pairs = {}
#     for invs in df_source["investors"].fillna("").astype(str):
#         inv_list = [x.strip() for x in invs.replace("&",",").split(",") if x.strip()]
#         inv_list = list(dict.fromkeys(inv_list))  # de-dup within row
#         if len(inv_list) < 2: continue
#         for a,b in combinations(sorted(inv_list), 2):
#             key = f"{a} & {b}"
#             pairs[key] = pairs.get(key, 0) + 1
#     if not pairs: return pd.DataFrame(columns=["pair","count"])
#     s = pd.Series(pairs).sort_values(ascending=False).head(top_n)
#     return s.rename_axis("pair").reset_index(name="count")
# def plot_lollipop(series, title="", xlabel=""):
#     s = series.dropna()
#     labels = s.index.astype(str)
#     vals = s.values.astype(float)
# 
#     y = np.arange(len(vals))
#     fig, ax = plt.subplots()
#     ax.hlines(y=y, xmin=0, xmax=vals, color="#e5e7eb", linewidth=2)
#     ax.plot(vals, y, "o", markersize=7, linewidth=0, color=COL_GROWTH)  # heads
#     ax.set_yticks(y); ax.set_yticklabels(labels)
#     ax.set_xlabel(xlabel); ax.set_ylabel("")
#     ax.set_title(title)
#     style_axes(ax)
#     st.pyplot(fig, use_container_width=True)
# # --- Minimal city location dictionary (extend as needed) ---
# CITY_COORDS = {
#     # India
#     "Bengaluru": (12.9716, 77.5946), "Bangalore": (12.9716, 77.5946),
#     "Gurgaon": (28.4595, 77.0266),  "Gurugram": (28.4595, 77.0266),
#     "New Delhi": (28.6139, 77.2090), "Delhi": (28.6139, 77.2090),
#     "Mumbai": (19.0760, 72.8777), "Chennai": (13.0827, 80.2707),
#     "Pune": (18.5204, 73.8567), "Noida": (28.5355, 77.3910),
#     "Hyderabad": (17.3850, 78.4867), "Ahmedabad": (23.0225, 72.5714),
#     "Kolkata": (22.5726, 88.3639), "Jaipur": (26.9124, 75.7873),
#     "Chandigarh": (30.7333, 76.7794), "Kochi": (9.9312, 76.2673),
#     "Coimbatore": (11.0168, 76.9558), "Indore": (22.7196, 75.8577),
#     "Vadodara": (22.3072, 73.1812), "Trivandrum": (8.5241, 76.9366),
#     # Global
#     "San Francisco": (37.7749, -122.4194), "New York": (40.7128, -74.0060),
#     "London": (51.5074, -0.1278), "Singapore": (1.3521, 103.8198),
#     "Berlin": (52.5200, 13.4050), "Paris": (48.8566, 2.3522),
#     "Dubai": (25.2048, 55.2708), "Hong Kong": (22.3193, 114.1694),
#     # Fallback bucket
#     "Not Specified": (None, None),
# }
# 
# 
# 
# # ===========================
# # Demography Analysis (Plotly)
# # ===========================
# def load_demography_analysis():
#     st.title("Demography Analysis")
#     st.caption(f"Data source: {data_src}")
#     st.markdown('<div class="section"></div>', unsafe_allow_html=True)
# 
#     # ---- Clean city + numeric amount ----
#     BAD = {"na","n/a","none","null","nan","-","—","--",""}
#     d0 = df.copy()
#     d0["city"] = d0["city"].astype(str).str.strip()
#     d0 = d0[~d0["city"].str.lower().isin(BAD)]
#     d0["amount"] = pd.to_numeric(d0["amount"], errors="coerce")
#     d0 = d0.dropna(subset=["amount"])
#     if d0.empty:
#         st.info("No usable city or amount information found.")
#         return
# 
#     # ---- Aggregate by city ----
#     city_agg = (
#         d0.groupby("city", as_index=False)
#           .agg(amount=("amount","sum"), deals=("startup","count"))
#           .sort_values("amount", ascending=False)
#           .reset_index(drop=True)
#     )
# 
#     # ---- Controls (inline) ----
#     c1, c2, c3 = st.columns([1.2, 1, 1])
#     with c1:
#         top_n = st.slider("Top N Cities", min_value=5, max_value=int(min(100, max(5, len(city_agg)))), value=min(15, len(city_agg)), step=1)
#     with c2:
#         scope = st.selectbox("Map Region", ["world","india","asia","usa","europe"], index=0)
#     with c3:
#         exclude_unknown = st.checkbox("Exclude 'Not Specified'", value=True)
# 
#     work = city_agg.copy()
#     if exclude_unknown:
#         work = work[work["city"].str.lower() != "not specified"]
# 
#     # ---- Top-N slice for visuals ----
#     top_df = work.nlargest(top_n, "amount").copy()
# 
#     # ---- Bar-like but cleaner: lollipop with Plotly? We'll do a lean horiz bar (few bars asked) ----
#     # (We keep it visually light by removing grid and using your palette)
#     fig_bar = px.bar(
#         top_df.sort_values("amount", ascending=True),
#         x="amount", y="city", orientation="h",
#         text="amount",
#         color_discrete_sequence=[COL_GROWTH],  # palette fit
#         title=f"Top {len(top_df)} Cities by Total Funding"
#     )
#     fig_bar.update_traces(texttemplate="%{text:.0f}", textposition="outside", cliponaxis=False, marker_line_width=0)
#     fig_bar.update_layout(
#         margin=dict(l=140, r=20, t=50, b=40),
#         xaxis_title="Total Funding",
#         yaxis_title="",
#         plot_bgcolor="#ffffff",
#         paper_bgcolor="#ffffff",
#         font=dict(color="#111827"),
#         xaxis=dict(showgrid=True, gridcolor="#e5e7eb"),
#         yaxis=dict(showgrid=False),
#     )
#     st.plotly_chart(fig_bar, use_container_width=True, theme=None)
# 
#     st.markdown('<div class="section"></div>', unsafe_allow_html=True)
# 
#     # ---- Map data (attach coords) ----
#     coords_df = pd.DataFrame({
#         "city": list(CITY_COORDS.keys()),
#         "lat":  [CITY_COORDS[c][0] for c in CITY_COORDS],
#         "lon":  [CITY_COORDS[c][1] for c in CITY_COORDS],
#     })
#     map_df = (
#         work.merge(coords_df, on="city", how="left")
#             .dropna(subset=["lat","lon"])
#     )
# 
#     # Focus map on Top-N cities only
#     map_top = map_df.merge(top_df[["city"]], on="city", how="inner").copy()
#     if map_top.empty:
#         st.info("No coordinates available for selected cities. Extend CITY_COORDS to cover your cities.")
#         return
# 
#     # perceptual bubble scale
#     map_top["size"] = np.sqrt(map_top["amount"].clip(lower=1))  # gentle growth
#     # cap visible marker sizes
#     size_max = 35 if scope == "world" else 28
# 
#     # ---- Map ----
#     fig_geo = px.scatter_geo(
#         map_top,
#         lat="lat", lon="lon",
#         size="size",
#         hover_name="city",
#         hover_data={"amount":":,.0f", "deals":True, "lat":False, "lon":False, "size":False},
#         color_discrete_sequence=[COL_SEED],
#         title="Hotspots Map — bubbles by total funding"
#     )
# 
#     # Region scope: use geos
#     if scope == "india":
#         # zoom into India bbox (lon, lat)
#         fig_geo.update_geos(
#             scope="asia",
#             lonaxis_range=[68, 98],
#             lataxis_range=[6, 38],
#             showcountries=True, countrycolor="#e5e7eb"
#         )
#     elif scope != "world":
#         fig_geo.update_geos(scope=scope, showcountries=True, countrycolor="#e5e7eb")
#     else:
#         fig_geo.update_geos(showcountries=True, countrycolor="#e5e7eb")
# 
#     fig_geo.update_traces(marker=dict(line=dict(width=0), sizemode="area"), marker_sizemin=2)
#     fig_geo.update_layout(
#         margin=dict(l=10, r=10, t=50, b=0),
#         plot_bgcolor="#ffffff",
#         paper_bgcolor="#ffffff",
#         font=dict(color="#111827"),
#         legend=dict(orientation="h", yanchor="bottom", y=0.02, xanchor="left", x=0),
#     )
#     fig_geo.update_traces(marker_sizeref=(2.*max(map_top["size"])/(size_max**2)))
#     st.plotly_chart(fig_geo, use_container_width=True, theme=None)
# 
# 
# 
# 
# 
# #=============================
# #Executive summary page
# #=============================
# def load_executive_summary():
#     st.title("Executive Summary")
#     st.caption(f"Data source: {data_src}")
# 
#     # ---------- darker subtext + highlight styles ----------
#     st.markdown("""
#     <style>
#       .es-row { display:flex; gap:18px; align-items:flex-start; margin:14px 0 8px 0; }
#       .es-pill { width:8px; height:28px; border-radius:4px; background:#000000; margin-top:4px; flex:0 0 8px; }
#       .es-block h3 { margin:0; font-size:26px; line-height:1.05; }
#       .es-block p  { margin:2px 0 0 0; color:#1f2937; font-size:13px; }  /* darker than before */
#       .es-grid { display:grid; grid-template-columns: 1fr; gap:8px; }
#       @media (min-width:900px){ .es-grid{ grid-template-columns: 1fr 1fr; } }
#     </style>
#     """, unsafe_allow_html=True)
# 
#     # ---------- selectors ----------
#     years = sorted([int(y) for y in df["year"].dropna().unique().tolist()])
#     if not years:
#         st.info("No year information available in the dataset.")
#         return
#     latest_year = years[-1]
#     year = st.selectbox("Year (for year-specific stats)", years, index=len(years)-1)
# 
#     # ---------- exclude placeholders everywhere ----------
#     EXCLUDE_INV  = {"others","other","na","n/a","none","null","nan","-","—","--","undisclosed",""}
#     EXCLUDE_VERT = {"na","n/a","none","null","nan","-","—","--",""}
# 
#     dfv = df.copy()
#     # clean vertical
#     dfv["vertical"] = dfv["vertical"].astype(str)
#     dfv = dfv[~dfv["vertical"].str.strip().str.lower().isin(EXCLUDE_VERT)]
# 
#     # investor-expanded with exclusions
#     dfe = df_exp.copy()
#     dfe["investor"] = dfe["investor"].astype(str)
#     dfe = dfe[~dfe["investor"].str.strip().str.lower().isin(EXCLUDE_INV)]
# 
#     # year slices
#     dfv_year = dfv[dfv["year"] == year].copy()
#     dfe_year  = dfe[dfe["year"] == year].copy()
# 
#     # ---------- metrics (all computed from cleaned data) ----------
#     MEGA_CR = 100.0  # threshold for mega deal (in Cr)
# 
#     total_funding_cr = float(dfv["amount"].sum())
#     deals_in_year     = int(len(dfv_year))              # <-- updates with year
#     mega_deals_total  = int((dfv["amount"] >= MEGA_CR).sum())
# 
#     # share of selected year in the last 5 available years
#     five_start = max(years[0], latest_year - 4)
#     last5_mask = (dfv["year"].between(five_start, latest_year))
#     last5_total = float(dfv.loc[last5_mask, "amount"].sum())
#     selected_year_total = float(dfv_year["amount"].sum())
#     share_year_in_last5 = (selected_year_total / last5_total * 100.0) if last5_total > 0 else 0.0
# 
#     # top sector overall (by amount) — using cleaned verticals
#     if not dfv.empty:
#         top_sector_all = dfv.groupby("vertical", dropna=False)["amount"].sum().sort_values(ascending=False).head(1)
#         top_sector_name = top_sector_all.index[0] if not top_sector_all.empty else "—"
#     else:
#         top_sector_name = "—"
# 
#     # top 1–2 sectors in selected year
#     top_sectors_year = (dfv_year.groupby("vertical")["amount"].sum()
#                         .sort_values(ascending=False).head(2))
#     top_sectors_year_label = " & ".join(top_sectors_year.index.astype(str)) if not top_sectors_year.empty else "—"
# 
#     # most active investor in selected year
#     if not dfe_year.empty:
#         ti = dfe_year.groupby("investor")["startup"].count().sort_values(ascending=False).head(1)
#         top_investor_year = ti.index[0] if not ti.empty else "—"
#     else:
#         top_investor_year = "—"
# 
#     # contribution of top 5 investors to total deal count (overall, cleaned)
#     if not dfe.empty:
#         inv_counts = dfe.groupby("investor")["startup"].count().sort_values(ascending=False)
#         top5_sum = int(inv_counts.head(5).sum())
#         total_investor_deals = int(inv_counts.sum())
#         top5_contrib_pct = (top5_sum / total_investor_deals * 100.0) if total_investor_deals > 0 else 0.0
#     else:
#         top5_contrib_pct = 0.0
# 
#     # ---------- KPI strip ----------
#     k1,k2,k3,k4,k5 = st.columns(5)
#     with k1: st.metric("All-time Funding", f"{total_funding_cr:,.1f} USD")
#     with k2: st.metric(f"Deals in {year}", f"{deals_in_year:,}")     # <-- dynamic now
#     with k3: st.metric(f"Mega-deals (≥{MEGA_CR:.0f} USD)", f"{mega_deals_total:,}")
#     with k4: st.metric("Top Sector (All-time)", top_sector_name)
#     with k5: st.metric(f"{year} Share of Last 5Y", f"{share_year_in_last5:,.1f}%")
# 
#     st.markdown('<div class="section"></div>', unsafe_allow_html=True)
# 
#     # ---------- Poster-style highlight rows ----------
#     st.markdown('<div class="es-grid">', unsafe_allow_html=True)
# 
#     # 1) Year funding + deals
#     st.markdown(f"""
#     <div class="es-row">
#       <div class="es-pill"></div>
#       <div class="es-block">
#         <h3>{selected_year_total:,.1f} USD</h3>
#         <p>Funding raised in {year} across {deals_in_year} deals</p>
#       </div>
#     </div>
#     """, unsafe_allow_html=True)
# 
#     # 2) Share of year in last 5y total
#     st.markdown(f"""
#     <div class="es-row">
#       <div class="es-pill" style="background:{COL_GROWTH};"></div>
#       <div class="es-block">
#         <h3>{share_year_in_last5:,.1f}%</h3>
#         <p>Share of {year} in total funding of the last 5 years ({five_start}–{latest_year})</p>
#       </div>
#     </div>
#     """, unsafe_allow_html=True)
# 
# 
# 
#     # 4) Most funded sector overall
#     st.markdown(f"""
#     <div class="es-row">
#       <div class="es-pill" style="background:{COL_SEED};"></div>
#       <div class="es-block">
#         <h3>{top_sector_name}</h3>
#         <p>Most funded sector overall</p>
#       </div>
#     </div>
#     """, unsafe_allow_html=True)
# 
#     # 5) Sectors bagging most funding in {year}
#     st.markdown(f"""
#     <div class="es-row">
#       <div class="es-pill" style="background:{COL_BRIDGE};"></div>
#       <div class="es-block">
#         <h3>{top_sectors_year_label}</h3>
#         <p>Bagged the most funding in {year}</p>
#       </div>
#     </div>
#     """, unsafe_allow_html=True)
# 
#     # 6) Contribution of top 5 investors
#     st.markdown(f"""
#     <div class="es-row">
#       <div class="es-pill" style="background:{COL_COUNT};"></div>
#       <div class="es-block">
#         <h3>{top5_contrib_pct:,.0f}%</h3>
#         <p>Contribution of top 5 investors to the total deal count</p>
#       </div>
#     </div>
#     """, unsafe_allow_html=True)
# 
#     # 7) Most active investor this year
#     st.markdown(f"""
#     <div class="es-row">
#       <div class="es-pill"></div>
#       <div class="es-block">
#         <h3>{top_investor_year}</h3>
#         <p>Most active investor in {year} (by number of deals)</p>
#       </div>
#     </div>
#     """, unsafe_allow_html=True)
# 
#     st.markdown('</div>', unsafe_allow_html=True)
# 
# 
# 
# 
# 
# 
# # ===========================
# # Investor page
# # ===========================
# def load_investor_details(investor: str):
#     st.title(investor); st.caption(f"Data source: {data_src}")
# 
#     inv_df = df_exp[df_exp["investor"] == investor].copy()
#     if inv_df.empty:
#         st.info("No records found for this investor."); return
# 
#     cols = ["date","startup","vertical","city","round","amount"]
#     st.subheader("Most Recent Investments"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#     st.dataframe(inv_df.sort_values("date", ascending=False)[cols].head(5), use_container_width=True)
# 
#     col1, col2 = st.columns(2)
#     with col1:
#         st.subheader("Biggest Investment (by Startup Total)"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         biggest = inv_df.groupby("startup", dropna=False)["amount"].sum().sort_values(ascending=False).head(5)
#         plot_bar(biggest.index, biggest.values, rotation=15, ylabel="Amount (Cr)")
#     with col2:
#         st.subheader("Sectors Invested In (by Amount)"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         verticals = inv_df.groupby("vertical", dropna=False)["amount"].sum().sort_values(ascending=False).head(10)
#         plot_barh_top(verticals, title="Top Sectors", xlabel="Amount (Cr)")
# 
#     col3, col4 = st.columns(2)
#     with col3:
#         st.subheader("Rounds Invested In (by Number of Deals)"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         rounds_cnt = inv_df["round"].value_counts().head(8)
#         colors = [color_for_round(r) for r in rounds_cnt.index]
#         fig, ax = plt.subplots()
#         ax.barh(rounds_cnt.index[::-1], rounds_cnt.values[::-1], color=colors[::-1])
#         bar_labels(ax, ax.containers[0])
#         ax.set_xlabel("Deal Count"); ax.set_ylabel(""); ax.set_title("Rounds by Count"); style_axes(ax)
#         st.pyplot(fig, use_container_width=True)
#     with col4:
#         st.subheader(f"Cities where {investor} Invests (by Deals)"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         cities_cnt = inv_df["city"].value_counts().head(10)
#         plot_barh_top(cities_cnt, title="Top Cities", xlabel="Deal Count")
# 
#     st.subheader("YoY Investments (Amount)"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#     yoy = inv_df.groupby("year", dropna=True)["amount"].sum().sort_index()
#     x = yoy.index.astype(int, errors="ignore")
#     plot_line_with_gradient(x, yoy.values, title="", color=COL_COUNT, xlabel="Year", ylabel="Amount (Cr)")
# 
#     # Similar investors
#     def safe_mode(series, default="N/A"):
#         if series is None or series.empty: return default
#         m = series.mode(dropna=True); return default if m.empty else str(m.iloc[0])
#     sel_vertical = safe_mode(inv_df["vertical"]); sel_subvertical = safe_mode(inv_df["subvertical"])
#     sim = df_exp[(df_exp["vertical"] == sel_vertical) & (df_exp["subvertical"] == sel_subvertical)]
#     if sim.empty: sim = df_exp[(df_exp["vertical"] == sel_vertical) | (df_exp["subvertical"] == sel_subvertical)]
#     similar_investors = (sim[sim["investor"] != investor].groupby("investor", dropna=False)["amount"]
#                          .sum().sort_values(ascending=False).head(10).reset_index())
#     st.subheader(f"Investors similar to {investor} in the '{sel_vertical}' vertical"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#     st.dataframe(similar_investors, use_container_width=True)
# 
# # ===========================
# # Startup page
# # ===========================
# def load_startup_details(startup: str):
#     st.title(startup); st.caption(f"Data source: {data_src}")
# 
#     s_df = df[df["startup"] == startup].copy()
#     if s_df.empty:
#         st.info("No records found for this startup."); return
# 
#     def safe_mode(series, default="N/A"):
#         if series is None or series.empty: return default
#         m = series.mode(dropna=True); return default if m.empty else str(m.iloc[0])
# 
#     col1, col2 = st.columns(2)
#     with col1:
#         st.subheader("Industry"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         st.text(safe_mode(s_df["vertical"]))
#     with col2:
#         st.subheader("SubIndustry"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         st.text(safe_mode(s_df["subvertical"]))
# 
#     col1, col2 = st.columns(2)
#     with col1:
#         st.subheader("Location"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         st.text(safe_mode(s_df["city"]))
#     with col2:
#         st.subheader("Total Funded Rounds"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         st.text(s_df.shape[0])
# 
#     st.header("Investments"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#     temp = s_df.sort_values("date", ascending=False)[["date","investors","round","amount"]]
#     st.dataframe(temp, use_container_width=True)
# 
#     st.subheader("Top Investors (by Amount)"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#     tmp = temp.copy()
#     tmp["investor_list"] = tmp["investors"].fillna("").astype(str).apply(lambda s: [x.strip() for x in s.replace("&",",").split(",")] if s else [])
#     tmp = tmp.explode("investor_list")
#     top_investors = tmp.groupby("investor_list", dropna=False)["amount"].sum().sort_values(ascending=False).head(10)
#     plot_barh_top(top_investors, title="Share by Investor", xlabel="Amount (Cr)")
# 
#     sel_vertical = safe_mode(s_df["vertical"]); sel_subvertical = safe_mode(s_df["subvertical"])
#     sim = df[(df["vertical"] == sel_vertical) & (df["subvertical"] == sel_subvertical)]
#     if sim.empty: sim = df[(df["vertical"] == sel_vertical) | (df["subvertical"] == sel_subvertical)]
#     similar_startups = (sim[sim["startup"] != startup]["startup"].value_counts().head(10)
#                         .rename_axis("startup").reset_index(name="freq"))
#     st.subheader(f"Startups similar to {startup} in the '{sel_vertical}' vertical"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#     st.dataframe(similar_startups, use_container_width=True)
# 
# # ===========================
# # Investor Analysis page (cleaned & minimal headers)
# # ===========================
# def load_investor_analysis():
#     st.title("Investor Analysis")
#     st.caption(f"Data source: {data_src}")
# 
#     # Exclude junk/placeholder investor names
#     EXCLUDE_INV = {
#         "others","other","other investor","other investors",
#         "misc","various","undisclosed","undisclosed investor","undisclosed investors",
#         "na","n/a","none","null","nil","nan","-","—","--",""
#     }
# 
#     def is_valid_investor(s):
#         if not isinstance(s, str):
#             return False
#         return s.strip().lower() not in EXCLUDE_INV
# 
#     # Filter cleaned investor expansion
#     dfe = df_exp[df_exp["investor"].apply(is_valid_investor)].copy()
# 
#     # ------- Main graph: Most active investors -------
#     st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#     top_by_count = (
#         dfe.groupby("investor", dropna=False)["startup"]
#            .count()
#            .sort_values(ascending=False)
#            .head(20)
#     )
#     plot_barh_top(top_by_count, title="Most Active Investors (Deals)", xlabel="Deal Count")
# 
#     # ------- Side-by-side: total amount & average ticket size -------
#     c1, c2 = st.columns(2)
#     with c1:
#         st.subheader("Top Investors by Total Amount Deployed")
#         st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         top_by_amount = (
#             dfe.groupby("investor", dropna=False)["amount"]
#                .sum()
#                .sort_values(ascending=False)
#                .head(20)
#         )
#         plot_barh_top(top_by_amount, title="By Amount", xlabel="Amount (USD)", fmt_vals="{:,.1f}")
# 
#     with c2:
#         st.subheader("Top Investors by Average Ticket Size")
#         st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         agg = (
#             dfe.groupby("investor", dropna=False)
#                .agg(deals=("startup","count"), amt=("amount","sum"))
#         )
#         agg["avg_ticket"] = agg["amt"] / agg["deals"]
#         top_avg = agg.sort_values("avg_ticket", ascending=False).head(20)["avg_ticket"]
#         plot_barh_top(top_avg, title="Avg per Deal", xlabel="Amount (USD)", fmt_vals="{:,.1f}")
# 
#     # ------- Investor × Sector Heatmap -------
#     st.subheader("Investor Focus by Sector (Top Investors × Top Sectors)")
#     st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#     top_inv = top_by_count.head(15).index
#     top_vert = df["vertical"].value_counts().head(12).index
# 
#     iv_pivot = (
#         dfe[dfe["investor"].isin(top_inv) & dfe["vertical"].isin(top_vert)]
#         .pivot_table(index="investor", columns="vertical", values="startup", aggfunc="count", fill_value=0)
#     )
# 
#     fig, ax = plt.subplots()
#     cmap = LinearSegmentedColormap.from_list("inv_vert_map", [COL_SEED, COL_LATE, COL_GROWTH], N=256)
#     sns.heatmap(iv_pivot, annot=True, fmt=".0f", cmap=cmap, ax=ax, cbar_kws={"shrink": .9, "label": "Deals"})
#     ax.set_xlabel("Sector"); ax.set_ylabel("")
#     style_axes(ax)
#     st.pyplot(fig, use_container_width=True)
# 
#     # ------- Co-investor pairs -------
#     st.subheader("Top Co-Investor Pairs (Shared Deals)")
#     st.markdown('<div class="section"></div>', unsafe_allow_html=True)
# 
#     from itertools import combinations
# 
#     def clean_investor_list(cell):
#         if pd.isna(cell): return []
#         raw = str(cell).replace("&", ",").split(",")
#         out = []
#         for p in raw:
#             p = p.strip()
#             if not p or p.lower() in EXCLUDE_INV:
#                 continue
#             out.append(p)
#         return list(dict.fromkeys(out))
# 
#     pairs_counts = {}
#     for cell in df["investors"].fillna(""):
#         invs = clean_investor_list(cell)
#         if len(invs) < 2:
#             continue
#         for a, b in combinations(sorted(invs), 2):
#             key = f"{a} & {b}"
#             pairs_counts[key] = pairs_counts.get(key, 0) + 1
# 
#     if pairs_counts:
#         s = pd.Series(pairs_counts).sort_values(ascending=False).head(15)
#         plot_barh_top(s, title="Frequent Co-Investors", xlabel="Shared Deals")
#     else:
#         st.info("Not enough co-investment data to display pairs.")
# 
# 
# 
# # ===========================
# # Overall analysis
# # ===========================
# def load_overall_analysis():
#     st.title("Overall Analysis"); st.caption(f"Data source: {data_src}")
# 
#     total = round(df["amount"].sum())
#     max_amt = round(df.groupby("startup", dropna=False)["amount"].max().max())
#     avg = round(df["amount"].mean(), 2)
#     funded_startups = df["startup"].nunique()
# 
#     c1, c2, c3, c4 = st.columns(4)
#     with c1: st.metric("Total", f"{total} Cr")
#     with c2: st.metric("Maximum", f"{max_amt} Cr")
#     with c3: st.metric("Average", f"{avg} Cr")
#     with c4: st.metric("Funded Startups", str(funded_startups))
# 
#     st.header("MoM Investments"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#     selected_option = st.selectbox("Select Type", ["Total", "Count"])
#     if selected_option == "Total":
#         temp_df = df.groupby(["year","month"], dropna=True)["amount"].sum().reset_index()
#         y_col, line_color = "amount", COL_COUNT
#     else:
#         temp_df = df.groupby(["year","month"], dropna=True)["amount"].count().reset_index().rename(columns={"amount":"count"})
#         y_col, line_color = "count", COL_COUNT
#     temp_df["x_axis"] = temp_df["month"].astype("Int64").astype(str).str.zfill(2) + "-" + temp_df["year"].astype("Int64").astype(str)
#     plot_line_with_gradient(temp_df["x_axis"], temp_df[y_col], color=line_color,
#                             xlabel="Month-Year", ylabel=("Amount (Cr)" if selected_option=="Total" else "Deal Count"),
#                             xtick_rotation=90)
# 
#     c1, c2 = st.columns(2)
#     with c1:
#         st.subheader("Top 10 Sectors by Number of Investments"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         top10_cnt = df["vertical"].value_counts().nlargest(10)
#         plot_barh_top(top10_cnt, title="By Count", xlabel="Deal Count")
#     with c2:
#         st.subheader("Top 10 Sectors by Total Amount Invested"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         top10_amt = df.groupby("vertical", dropna=False)["amount"].sum().sort_values(ascending=False).head(10)
#         plot_barh_top(top10_amt, title="By Amount", xlabel="Amount (Cr)")
# 
#     c1, c2 = st.columns(2)
#     with c1:
#         st.subheader("Top 5 Funding Rounds by Number of Deals"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         rounds_by_count = df["round"].value_counts().head(5)
#         colors = [color_for_round(r) for r in rounds_by_count.index]
#         fig, ax = plt.subplots()
#         ax.barh(rounds_by_count.index[::-1], rounds_by_count.values[::-1], color=colors[::-1])
#         bar_labels(ax, ax.containers[0]); ax.set_xlabel("Deal Count"); ax.set_ylabel("")
#         ax.set_title("Rounds by Count"); style_axes(ax); st.pyplot(fig, use_container_width=True)
#     with c2:
#         st.subheader("Top 5 Funding Rounds by Amount Raised"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         rounds_by_amount = df.groupby("round", dropna=False)["amount"].sum().sort_values(ascending=False).head(5)
#         colors = [color_for_round(r) for r in rounds_by_amount.index]
#         fig, ax = plt.subplots()
#         ax.barh(rounds_by_amount.index[::-1], rounds_by_amount.values[::-1], color=colors[::-1])
#         bar_labels(ax, ax.containers[0], fmt="{:,.1f}")
#         ax.set_xlabel("Amount (Cr)"); ax.set_ylabel(""); ax.set_title("Rounds by Amount"); style_axes(ax)
#         st.pyplot(fig, use_container_width=True)
# 
#     c1, c2 = st.columns(2)
#     with c1:
#         st.subheader("Top 10 Cities by Number of Fundings"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         top_cities_cnt = df["city"].value_counts().head(10)
#         plot_barh_top(top_cities_cnt, title="By Count", xlabel="Deal Count")
#     with c2:
#         st.subheader("Top 10 Cities by Total Funding Amount"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         top_cities_amt = df.groupby("city", dropna=False)["amount"].sum().sort_values(ascending=False).head(10)
#         plot_barh_top(top_cities_amt, title="By Amount", xlabel="Amount (Cr)")
# 
#     c1, c2 = st.columns(2)
#     with c1:
#         st.subheader("Yearly Top Startups (by Amount)"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         top_startups = (df.groupby(["startup","year"], dropna=True)["amount"].sum()
#                         .sort_values(ascending=False).reset_index()
#                         .drop_duplicates("year", keep="first").sort_values("year", ascending=False))
#         top_startups["x_axis"] = top_startups["startup"] + "-" + top_startups["year"].astype("Int64").astype(str)
#         plot_barh_top(pd.Series(top_startups["amount"].values, index=top_startups["x_axis"]), title="", xlabel="Amount (Cr)")
#     with c2:
#         st.subheader("Yearly Top Investors (by Amount)"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#         top_investors = (df_exp.groupby(["investor","year"], dropna=True)["amount"].sum()
#                          .sort_values(ascending=False).reset_index()
#                          .drop_duplicates("year", keep="first").sort_values("year", descending=False))
#         top_investors["x_axis"] = top_investors["investor"] + "-" + top_investors["year"].astype("Int64").astype(str)
#         plot_barh_top(pd.Series(top_investors["amount"].values, index=top_investors["x_axis"]), title="", xlabel="Amount (Cr)")
# 
#     st.header("Funding Heatmap"); st.markdown('<div class="section"></div>', unsafe_allow_html=True)
#     funding_selected = st.selectbox("Select Heatmap", ["Total Amount", "Total Investments"])
#     if funding_selected == "Total Amount":
#         heatmap_data = pd.pivot_table(df, columns="year", index="month", values="amount", aggfunc="sum")
#         fmt = ".1f"
#         cmap = LinearSegmentedColormap.from_list("amt_map", [COL_SEED, COL_LATE, COL_GROWTH], N=256)
#     else:
#         heatmap_data = pd.pivot_table(df, columns="year", index="month", values="amount", aggfunc="count")
#         fmt = ".0f"
#         cmap = LinearSegmentedColormap.from_list("cnt_map", [COL_SEED, COL_COUNT, COL_BRIDGE], N=256)
#     fig, ax = plt.subplots()
#     sns.heatmap(heatmap_data, annot=True, fmt=fmt, cmap=cmap, ax=ax, cbar_kws={"shrink": .9, "label": funding_selected})
#     ax.set_ylabel("Month"); ax.set_xlabel("Year"); style_axes(ax)
#     st.pyplot(fig, use_container_width=True)
# 
# # ===========================
# # Sidebar & Routing
# # ===========================
# st.sidebar.title('Startup Funding Analysis')
# # add "Executive Summary" to options
# option = st.sidebar.selectbox(
#     "Select One",
#     ["Overall Analysis", "StartUp", "Investor", "Investor Analysis", "Executive Summary","Demography Analysis"]
# )
# 
# # route
# if option == "Overall Analysis":
#     load_overall_analysis()
# elif option == "StartUp":
#     startup = st.sidebar.selectbox("Select StartUp", sorted(df["startup"].dropna().unique().tolist()))
#     if st.sidebar.button("Find StartUp Details"):
#         load_startup_details(startup)
# elif option == "Investor Analysis":
#     load_investor_analysis()
# elif option == "Demography Analysis":
#     load_demography_analysis()
# 
# elif option == "Executive Summary":
#     load_executive_summary()
# else:
#     investors_list = sorted([x for x in df_exp["investor"].dropna().unique().tolist() if x])
#     investor = st.sidebar.selectbox("Select Investor", investors_list)
#     if st.sidebar.button("Find Investor Details"):
#         load_investor_details(investor)
# 
# 
# 
#

from google.colab import files
uploaded = files.upload()  # choose your cleaned CSV

# If your file isn't named 'dataframe_output.csv', rename it here:
import os, shutil
fname = next(iter(uploaded))
if fname != "dataframe_output.csv":
    shutil.move(fname, "dataframe_output.csv")
print("Ready → dataframe_output.csv")

# === Cell 3: install ngrok v3 and set authtoken ===
import shutil, subprocess, os, tarfile, urllib.request
from getpass import getpass

def install_ngrok():
    if shutil.which("ngrok"):
        print("ngrok already installed at:", shutil.which("ngrok"))
        return
    url = "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz"
    tgz = "/tmp/ngrok.tgz"
    print("Downloading ngrok v3...")
    urllib.request.urlretrieve(url, tgz)
    with tarfile.open(tgz, "r:gz") as tar:
        tar.extractall("/usr/local/bin")
    os.chmod("/usr/local/bin/ngrok", 0o755)
    print("ngrok installed to /usr/local/bin/ngrok")

install_ngrok()

# Add your authtoken (only if not already set)
cfg = os.path.expanduser("~/.config/ngrok/ngrok.yml")
if not os.path.exists(cfg):
    token = getpass("Paste your NGROK_AUTH_TOKEN: ")
    assert token.strip(), "Empty token."
    subprocess.check_call(["ngrok", "config", "add-authtoken", token.strip()])
    print("Authtoken saved to:", cfg)
else:
    print("ngrok config already present at:", cfg)

# === Cell 4: start Streamlit + ngrok (v3-safe) ===
import os, shutil, subprocess, time, socket, json, re, urllib.request

APP_FILE = "app.py"   # your script
PORT = 8501
REGION = "in"         # try "us" or "ap" if needed

def is_port_open(host, port, timeout=0.25):
    import socket
    try:
        s = socket.socket(); s.settimeout(timeout)
        s.connect((host, port)); s.close()
        return True
    except Exception:
        return False

# sanity checks
assert os.path.exists(APP_FILE), f"{APP_FILE} not found."
assert shutil.which("streamlit"), "Streamlit not found. Re-run install cell."
assert shutil.which("ngrok"), "ngrok not found. Run the ngrok install cell."

# free PORT if busy
if is_port_open("127.0.0.1", PORT):
    print(f"Freeing port {PORT}...")
    get_ipython().system(f"fuser -k {PORT}/tcp")
    time.sleep(1)

# start Streamlit
print("▶ Starting Streamlit...")
env = os.environ.copy()
env["STREAMLIT_SERVER_HEADLESS"] = "true"
env["STREAMLIT_BROWSER_GATHER_USAGE_STATS"] = "false"

streamlit_proc = subprocess.Popen(
    ["streamlit", "run", APP_FILE, "--server.port", str(PORT), "--server.address", "0.0.0.0"],
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, env=env
)

# wait for server
t0 = time.time()
while not is_port_open("127.0.0.1", PORT) and time.time() - t0 < 45:
    time.sleep(0.5)

if not is_port_open("127.0.0.1", PORT):
    print("❌ Streamlit failed to start. Last 80 lines:")
    try:
        logs = []
        for _ in range(400):
            line = streamlit_proc.stdout.readline()
            if not line: break
            logs.append(line.rstrip())
        for ln in logs[-80:]:
            print(ln)
    except Exception:
        pass
    raise SystemExit("Fix Streamlit errors above and re-run this cell.")

# start ngrok (v3). Note: no --webaddr flag in v3.
print("▶ Starting ngrok tunnel…")
ngrok_cmd = [
    "ngrok", "http",
    f"--region={REGION}",
    "--log=stdout",
    "--log-format=json",
    str(PORT)
]
ngrok_proc = subprocess.Popen(ngrok_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)

def fetch_from_api(timeout=35):
    """Try ngrok local API (usually on :4040)."""
    api = "http://127.0.0.1:4040/api/tunnels"
    start = time.time()
    last_err = None
    while time.time() - start < timeout:
        try:
            with urllib.request.urlopen(api, timeout=2) as r:
                data = json.loads(r.read().decode("utf-8"))
                for t in data.get("tunnels", []):
                    u = t.get("public_url", "")
                    if u.startswith("https://"):
                        return u
                if data.get("tunnels"):
                    return data["tunnels"][0].get("public_url")
        except Exception as e:
            last_err = e
        time.sleep(1)
    if last_err:
        print("API last error:", repr(last_err))
    return None

def fetch_from_logs(timeout=70):
    """Fallback: parse public_url from JSON logs."""
    start = time.time()
    pattern = re.compile(r'"public_url":"(https://[^"]+)"')
    while time.time() - start < timeout:
        line = ngrok_proc.stdout.readline()
        if not line:
            time.sleep(0.2)
            continue
        m = pattern.search(line)
        if m:
            return m.group(1)
    return None

public_url = fetch_from_api() or fetch_from_logs()

print("✅ Streamlit URL:", public_url or "(not found)")
if not public_url:
    print("\n--- ngrok logs (tail) ---")
    for _ in range(120):
        line = ngrok_proc.stdout.readline()
        if not line: break
        print(line.rstrip())
    print("\nTips:")
    print("• Ensure your ngrok authtoken is set (Cell 3).")
    print("• Free old tunnels in ngrok dashboard (free tier allows 1).")
    print("• Try REGION='us' or 'ap'.")